# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mooov' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mooov
  pod 'Firebase/Analytics'
  pod 'Firebase/AppDistribution'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'


  target 'MooovTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MooovUITests' do
    # Pods for testing
  end

end
